version: '2'
services:
    progesto-app:
        image: progesto
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://progesto-postgresql:5432/progesto
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    progesto-postgresql:
        extends:
            file: postgresql.yml
            service: progesto-postgresql
